### ISSUE TITLE
Error using colors.

### ISSUE THREAD

**Issue by sellout** [softwaremill/scala-clippy#32]
When I add `scalacOptions += "-P:clippy:colors=true"` to ~/.sbt/0.13/global.sbt, I get an error: “java.lang.ClassCastException: com.softwaremill.clippy.DelegatingReporter cannot be cast to xsbt.DelegatingReporter”

Without the scalac arg, clippy works great.

**Comment by kciesielski** [comment]
Hi Greg,  this is fixed by #31, release later today.

On Jan 12, 2017 16:07, "Greg Pfeil" <notifications@github.com> wrote:

When I add scalacOptions += "-P:clippy:colors=true" to
~/.sbt/0.13/global.sbt, I get an error: “java.lang.ClassCastException:
com.softwaremill.clippy.DelegatingReporter cannot be cast to
xsbt.DelegatingReporter”

Without the scalac arg, clippy works great.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/softwaremill/scala-clippy/issues/32>, or mute the thread

**Comment by adamw** [comment]
@sellout Could you test 0.3.6? "should" work, but with all this mutable state in the compiler... ;)

**Comment by sellout** [comment]
Yep. It works. Thanks!

**Comment by kciesielski** [comment]
The issue still occurs for multi-module projects. A fix is on the way.

**Comment by kciesielski** [comment]
Should be fully fixed now by #33.
